### ISSUE TITLE
IDEA: Make an option for the script to make a tiktok story.

### ISSUE THREAD

**Issue by Denotess** [JasonLovesDoggo/RedditVideoMakerBot#10]
So the script would take threads from r/stories but instead of reading the comments, it would just read the story and adjust the video length to the story. If the story is too long (over 3 mins) it would make multiple parts.

**Comment by JasonLovesDoggo** [comment]
guess I got time!

**Comment by edvinas1** [comment]
If you need just story without comments: content["thread_title"] = submission.title+" "+ submission.selftext  in /reddit/subreddit.py it just created video of title and story ignoring comments 3+ min. long  Tested on one video so it could vary.

**Comment by StopmotionSimonYT** [comment]
Hi @JasonLovesDoggo, you added an in progress story mode. What is needed to make this complete? Or does it only needs to be tested?

**Comment by JasonLovesDoggo** [comment]
> Hi @JasonLovesDoggo, you added an in progress story mode. What is needed to make this complete? Or does it only needs to be tested?

I'm not exactly sure what needs to be done I think you need to sync the screenshots and mp3 audio and uncomment a line in Subreddit.py testing also needs to be done

**Comment by edvinas1** [comment]
> > Hi @JasonLovesDoggo, you added an in progress story mode. What is needed to make this complete? Or does it only needs to be tested?
> 
> I'm not exactly sure what needs to be done I think you need to sync the screenshots and mp3 audio and uncomment a line in Subreddit.py testing also needs to be done

If i understood correctly  there are no  submission.content ,submission.selftext refers to content, after changing it  and set STORYMODE="True" it look like everything  is working but i get some notifications ;
This install of SoX cannot process .mp3 files
Input formats were only specified for 0 out of 25 files.The last 25 files will remain unformatted.
This install of SoX cannot process .mp3 files.
unable to validate file formats.
Output file dose not contain story. If change content["thread_title"] = submission.title+" "+ submission.selftext in /reddit/subreddit.py it creates video of story but picture of story is to big.

**Comment by JasonLovesDoggo** [comment]
That's why it's still not implemented
