### ISSUE TITLE
OSError: MoviePy error: the file assets/mp3/0.mp3 could not be found! Please check that you entered the correct path.

### ISSUE THREAD

**Issue by allovertheglobe** [JasonLovesDoggo/RedditVideoMakerBot#14]
![image](https://user-images.githubusercontent.com/73898315/171475764-90c47381-8aac-48a6-ad4e-d693d2f250cf.png)

Bottom line of this, seems it has done everything else but just completing final video it cannot find this. Assets folder is empty but they are all in the temps folder?

**Comment by JasonLovesDoggo** [comment]
the program only really keeps the background videos in the assets and the audio clips and screenshots/ are stored in the temp folder and then deleted after the final video is made.

but yeah, that issue isn't just you, the same thing has happened to me, my advice rn is to just rerun the program as i only get that error like 1/6 runs. 

I don't yet know the actual cause of the error, and I'm not home so it's hard to debug it.

**Comment by allovertheglobe** [comment]
Tried running 3 times back to back and same issue - its definitely looking for the files in the ASSETS>MP3 folder rather than lookin in the temp folder mp3

**Comment by allovertheglobe** [comment]
Where did you put the results folder? Ive got one in the assets and the temp folders

**Comment by Denotess** [comment]
Over here: 
![image](https://user-images.githubusercontent.com/104372439/171478973-36be6856-e317-4b24-82cb-81c1e6968ca5.png)

**Comment by allovertheglobe** [comment]
Hmmm added this folder and same error remains

**Comment by StopmotionSimonYT** [comment]
I had the same error and removing the backgrounds.mp4 in the temp folder worked for me!

**Comment by allovertheglobe** [comment]
Don't have any MP4 in the temp folder for me - only MP3 folder in there

**Comment by StopmotionSimonYT** [comment]
![image](https://user-images.githubusercontent.com/65854503/171480195-943175cf-825e-48a3-9f9a-57493f76bae3.png)
I had this file in my temp folder

**Comment by allovertheglobe** [comment]
Added all of those folders.

Still just getting:

MoviePy error: the file assets/mp3/0.mp3 could not be found! Please check that you entered the correct path

I've tried changing the code to pull from the temp folder but resulted in more errors so reverted back

**Comment by allovertheglobe** [comment]
I've recloned and same issue as original image

**Comment by allovertheglobe** [comment]
I seen on another issue you said the latest version now doesnt show error, so I started fresh and tried again with a new clean version but same error:

![image](https://user-images.githubusercontent.com/73898315/171504929-2dec632a-1f7f-44b8-89dc-f21dbffdf3ce.png)

**Comment by stopmoclay** [comment]
I have the latest version and getting the same "0.mp3 does not exist" error even after adding the results folder, etc.

**Comment by JasonLovesDoggo** [comment]
Huh I never noticed that but I think you are correct. Huge help, thank you. I'm also going to add a tiny line of code that adds the results folder

**Comment by stopmoclay** [comment]
@JasonLovesDoggo Thanks for your incredible work on this, TTS voice is fantastic upgrade

**Comment by JasonLovesDoggo** [comment]
Thank you so much! I just didn't really fancy the GTTS results but I knew that the TikTok TTS sounded great so I found the API for that. I'm so glad it doesn't require authentication or anything like that

**Comment by stopmoclay** [comment]
Script is running well now but videos aren't appearing in "results" folder despite script saying that the video is created successfully

**Comment by JasonLovesDoggo** [comment]
Are you sure they're not there.... I don't see how they would get anywhere else but just check...

**Comment by stopmoclay** [comment]
I have a feeling it might be to do with changing which background videos are used, I'm gonna do a fresh pull and start over will post results

**Comment by allovertheglobe** [comment]
is it random whether it uses the minecraft or the orbital gameplay? seem to only get orbital

**Comment by JasonLovesDoggo** [comment]
Yeah it's random see the background.py file line 48

**Comment by stopmoclay** [comment]
When using the below videos, the script appears to fully complete and posts a success message but there is no video in the "results" folder

https://www.youtube.com/watch?v=hs7Z0JUgDeA
https://www.youtube.com/watch?v=Q5KtBKk4hC0

**Comment by stopmoclay** [comment]
Ok I think it might be something to do with the aspect ratio of those videos, using 1920x1080 videos and it works again

**Comment by JasonLovesDoggo** [comment]
huh..... that is very odd...

well, is there a chance you can send over some no ad yt videos that are 1920x1080p?

**Comment by JasonLovesDoggo** [comment]
well... I have an actual fix for this that you can use any res videos. but it's not tested yet and it's too late.

**Comment by JasonLovesDoggo** [comment]
> > well... I have an actual fix for this that you can use any res videos. but it's not tested yet and it's too late.
> 
> It’s crazy late where I am but would love to help test tomorrow!

sounds good! I'm just having a de-syncing issue where the sound and the ss don't match up.

will need more work.

**Comment by Proton45** [comment]
> I had the same error and removing the backgrounds.mp4 in the temp folder worked for me!

Thanks that worked for me! I dont really understand how that was causing an error, but I really dont care now that it works lol

**Comment by mrawesomey** [comment]
> Added results folder and got past 1st error...now downloading videos I will update if it works!

Still dont work for me get all the errors and even though I have Sox installed it doesnt show.
How do I fix it?

**Comment by mrawesomey** [comment]
> > Added results folder and got past 1st error...now downloading videos I will update if it works!
> 
> Still dont work for me get all the errors and even though I have Sox installed it doesnt show. How do I fix it?

I restarted it now it works but SoX still doesn't show, and how do I check the path?
