### ISSUE TITLE
no module named 'sox'

### ISSUE THREAD

**Issue by lesterrar** [JasonLovesDoggo/RedditVideoMakerBot#19]
![reg5](https://user-images.githubusercontent.com/44342036/171543017-c68c613b-0834-4fc9-beff-47cbfb35022f.PNG)

**Comment by FluxYT** [comment]
https://sourceforge.net/projects/sox/files/sox/ Here you go then click download latest version. Should fix the issue.

**Comment by lesterrar** [comment]
still the same error

**Comment by lesterrar** [comment]
pip install sox

**Comment by lesterrar** [comment]
this one worked
