### ISSUE TITLE
No such file videos.json

### ISSUE THREAD

**Issue by Milord-Mudkip** [JasonLovesDoggo/RedditVideoMakerBot#20]
giving this error but the file is there
![Screenshot 2022-06-02 145818](https://user-images.githubusercontent.com/101855989/171559248-b0b02dc6-652f-47a2-b84e-f963938419b0.png)
![Screenshot 2022-06-02 145848](https://user-images.githubusercontent.com/101855989/171559253-69d6bee1-bb18-462a-b19a-e12a8043dd67.png)
e

**Comment by JasonLovesDoggo** [comment]
honestly, as I have no way to debug this as it works on everybody else's machines... 
I don't know how to help you.

try testing the filepath with the os.mkdir() func
