### ISSUE TITLE
NSFW Filter Issue

### ISSUE THREAD

**Issue by Clumsy0420** [JasonLovesDoggo/RedditVideoMakerBot#21]
NSFW Filter Appears to be causing OSError: input_filepath assets/temp/mp3/6.mp3 does not exist. I Bypassed this issue by disabling the nsfw filter overall by in the screenshot_downloader.py going to line 38 and changing 
if getenv("ALLOW_NSFW").casefold() == "True":
toif getenv("ALLOW_NSFW").casefold() == "False":
Make sure to set .env file for allow nsfw to False

**Comment by Clumsy0420** [comment]
Btw this is a temp fix while the dev tries to figure out whats goin on!

**Comment by JasonLovesDoggo** [comment]
I do not believe there is a correlation between the NSFW filter and that error..
