### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.cleanup

### ISSUE THREAD

**Issue by BartGaming** [JasonLovesDoggo/RedditVideoMakerBot#24]
![Untitled](https://user-images.githubusercontent.com/90392738/171592212-3bfc2f2d-4da2-454a-b936-996fa5f92c80.png)

Tried doing: 'pip3 install utils.cleanup' but then I get:
![Untitled](https://user-images.githubusercontent.com/90392738/171592440-800ce723-d4ce-451d-b234-7f9ca1af37aa.png)
 
So I don't know how to fix this.

**Comment by JasonLovesDoggo** [comment]
try adding a empty __init__.py file in the utils folder
also, what python version are you on?

(sorry for the late reply)

**Comment by BartGaming** [comment]
im on python 3.10.4

**Comment by JasonLovesDoggo** [comment]
and did the file `__init__.py` file advice help?

**Comment by JasonLovesDoggo** [comment]
have you tried it yet?
I will be closing this in 12hrs
