### ISSUE TITLE
Filtering NSFW Words from Reddit's Comments.

### ISSUE THREAD

**Issue by Xiinergy** [JasonLovesDoggo/RedditVideoMakerBot#25]
Not an issue, but an enhancement.

Just got my tiktok account banned because of NFSW Words featured in one of the comments in reddit.
An enhancement would be to filter out those words.

**Comment by JasonLovesDoggo** [comment]
> Just got my tiktok account banned because of NFSW Words featured in one of the comments in Reddit.
An enhancement would be to filter out those words.

sorry.... 

yeah, that would need an extensive list of NSFW words so it knows what to filter but can definitely be done.
unfortunately  its pretty low on my TODO list

**Comment by JasonLovesDoggo** [comment]
note to self...
https://pypi.org/project/profanity-filter/

**Comment by JasonLovesDoggo** [comment]
update: this is a lot harder than anticipated

**Comment by edvinas1** [comment]
@JasonLovesDoggo could https://pypi.org/project/profanity-filter/ can be used on comment_body to filter out bad words? I dont know how to approach image part, but maybe use pytesseract to get position of words and use PIL to cover it ?

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo could https://pypi.org/project/profanity-filter/ can be used on comment_body to filter out bad words? I dont know how to approach image part, but maybe use pytesseract to get position of words and use PIL to cover it ?

I tried using that It doesn't work anymore

**Comment by edvinas1** [comment]
@JasonLovesDoggo https://pypi.org/project/better-profanity/ ?

**Comment by JasonLovesDoggo** [comment]
> Still need a hand? I have a rough implementation, but I don't know what words to use, but I do have a list.

Nah imma do it properly
