### ISSUE TITLE
IDEA: Make a option to could make multiple videos

### ISSUE THREAD

**Issue by IdkHowAreYOU** [JasonLovesDoggo/RedditVideoMakerBot#26]
So basicly to make X number of videos

**Comment by mrawesomey** [comment]
Please do this, but no stress

**Comment by JasonLovesDoggo** [comment]
will be done.

**Comment by JasonLovesDoggo** [comment]
also any who wants to do this
just add a for loop in the main.py file

**Comment by mrawesomey** [comment]
> also any who wants to do this just add a for loop in the main.py file e.i. `for x in range(NUMBER_OF_VIDEOS)`

Where do I put it and do I put a Number instead of NUMBER_OF_VIDEOS or do I do

NUMBER_OF_VIDEOS= 2 at the start of main.py?

**Comment by mrawesomey** [comment]
> code has been done will be pushed in the next update

When is it getting pushed?

**Comment by JasonLovesDoggo** [comment]
> > code has been done will be pushed in the next update
> 
> When is it getting pushed?
> 

As soon as it's bug free

**Comment by mrawesomey** [comment]
> also any who wants to do this just add a for loop in the main.py file e.i. `for x in range(NUMBER_OF_VIDEOS)`

Where do I put it in main.py (which line)

**Comment by JasonLovesDoggo** [comment]
At the top line of the if __name__ == thingo
Don't forget to indent
