### ISSUE TITLE
IDEA: Implement a "VOICE" value into the .env file

### ISSUE THREAD

**Issue by Proton45** [JasonLovesDoggo/RedditVideoMakerBot#28]
Pretty simple idea: Having the random voices can be kinda annoying so I would like to propose the idea of having a "VOICE" value in the .env file that decides what voice the bot is using. Even better would be a "TITLE_VOICE" and a "COMMENTS_VOICE" value.  

I.e.: "VOICE"="en_us_010"

**Comment by JasonLovesDoggo** [comment]
sure. 
will be done right after the SoX fix.
great Idea btw.

**Comment by JasonLovesDoggo** [comment]
(also for anyone who wants to do this just use os.getenv())

**Comment by JasonLovesDoggo** [comment]
doin now
