### ISSUE TITLE
OSError or AttributeError almost every run

### ISSUE THREAD

**Issue by Proton45** [JasonLovesDoggo/RedditVideoMakerBot#30]
Basically, every run results in an error. Here are the errors: 

OSError: input_filepath assets/temp/mp3/0.mp3 does not exist. / OSError: input_filepath assets/temp/mp3/5.mp3 does not exist.

AttributeError: 'dict' object has no attribute 'title'

IndexError: list index out of range

I don't really understand what is going wrong. I've tried deleting the temp/mp3 folder since another user suggested that in #14, but that doesn't seem to work for me. 
Does anyone know why this keeps happening and a solution?

**Comment by JasonLovesDoggo** [comment]
Shoot I know exactly how to fix this but I'm not going to be near a computer tonight so I can't fix it.

**Comment by Proton45** [comment]
> Shoot I know exactly how to fix this but I'm not going to be near a computer tonight so I can't fix it.

All good mate. Thank you so much for all the work you put in.
