### ISSUE TITLE
OSError: input_filepath assets\temp\mp3\0.mp3 does not exist.

### ISSUE THREAD

**Issue by tianiste** [JasonLovesDoggo/RedditVideoMakerBot#32]
Any Idea on why this is happening? If i rerun the program a few times it will work, but most of the times, this is showing up.
![image](https://user-images.githubusercontent.com/104372439/171872695-a2987151-5528-4adf-8262-1d752e1d4e1f.png)

**Comment by snappyy** [comment]
Yeah common bug I am experiencing this sometimes as well I just keep re-running it until it works but that's annoying as it normally only works for certain reddit threads which I'll already have a video on

**Comment by Proton45** [comment]
Seems to be a very common error. I think it is an issue with SoX. It seems like SoX doesn't work as intended. 
There is no fix for it yet.

**Comment by JasonLovesDoggo** [comment]
working on the fix RN

**Comment by mrawesomey** [comment]
Pls fix

**Comment by snappyy** [comment]
excited for this fix

**Comment by StopmotionSimonYT** [comment]
I am very excited for the fix

**Comment by JasonLovesDoggo** [comment]
lol.. so much excitement...

the fix is almost done!

**Comment by Diwas37** [comment]
is it fixed,cause I'm getting the error ?

**Comment by Diwas37** [comment]
oh...adding results folder inside RedditVideoMakerBot and emptying the post id (POST ID="") in .env solved the error for me...

**Comment by snappyy** [comment]
> oh...adding results folder inside RedditVideoMakerBot and emptying the post id (POST ID="") in .env solved the error for me... got the info from here #14
yeah I have that folder and also have left POST ID empty and I still run into this issue occasionally

**Comment by JasonLovesDoggo** [comment]
well the fix is basically done but im not going to be at  my pc for the next like day and a half so ;L 
see fp-fix branch for partial fix
