### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Emmes420** [JasonLovesDoggo/RedditVideoMakerBot#38]
![image](https://user-images.githubusercontent.com/48575205/171981182-c171972d-2e77-4a30-a5b0-17876ec01c9b.png)
Oss error

**Comment by Matt10233** [comment]
> ![image](https://user-images.githubusercontent.com/48575205/171981182-c171972d-2e77-4a30-a5b0-17876ec01c9b.png)
> 
> Oss error

Yes I have exactly the same problem, try a lot of times, it's working sometimes.

**Comment by mlvps** [comment]
removing the temp in the code works for me since my mp3 and mp4s are saved in the assets folder.

**Comment by snappyy** [comment]
> removing the temp in the code works for me since my mp3 and mp4s are saved in the assets folder.

in which file do you remove this code?

**Comment by mlvps** [comment]
> 

in final_video.py

**Comment by snappyy** [comment]
> > 
> 
> in final_video.py

sorry im really new to this kinda stuff could you paste your final_video.py for me?

**Comment by JasonLovesDoggo** [comment]
Keep in mind this will be fixed within the next 3 days
