### ISSUE TITLE
IDEA: Add opacity to reddit posts. It would make the overall video look cleaner

### ISSUE THREAD

**Issue by mlvps** [JasonLovesDoggo/RedditVideoMakerBot#39]

**Comment by JasonLovesDoggo** [comment]
I had the same idea I just do not know how to implement that.
Well without also having the text be partially transparent

**Comment by mlvps** [comment]
> I had the same idea I just do not know how to implement that.
> Well without also having the text be partially transparent

I think doing like 90% opacity wont harm the text that much. you would still be able to read everything perfectly, but it just would look better

**Comment by JasonLovesDoggo** [comment]
Sounds interesting I guess I could just do that

**Comment by JasonLovesDoggo** [comment]
But I'll add a config so you can set how transparent you want the image

**Comment by mlvps** [comment]
> But I'll add a config so you can set how transparent you want the image

yeah would be a good idea

**Comment by JasonLovesDoggo** [comment]
> Maybe this could help: https://github.com/elebumm/RedditVideoMakerBot/pull/270
> 
> I can try to implement this code tomorrow.

I can probably implement it today but yeah it definitely helps

**Comment by JasonLovesDoggo** [comment]
just implemented.
testing rn
