### ISSUE TITLE
IDEA: Add a little pause after every reddit post. It would make the video seem more natural

### ISSUE THREAD

**Issue by mlvps** [JasonLovesDoggo/RedditVideoMakerBot#40]

**Comment by JasonLovesDoggo** [comment]
Interesting idea.
Will probably be done but it's pretty low on my to-do list.

**Comment by mlvps** [comment]
> Interesting idea.
> Will probably be done but it's pretty low on my to-do list.

oh and btw is there a way to add a little pause between reading the posts title and description? because when the tts voice reads the title he instantly starts reading the description without any pause. it seems like its the same sentence and it sounds really bad.

**Comment by JasonLovesDoggo** [comment]
See above comment

**Comment by mlvps** [comment]
there isnt any pause for me
