### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Patrick1020** [JasonLovesDoggo/RedditVideoMakerBot#42]
when i run the program i am getting this error

![image](https://user-images.githubusercontent.com/78136826/172004523-cf81d33f-786b-488a-83c3-7b39a7bde457.png)

**Comment by Matt10233** [comment]
> when i run the program i am getting this error
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/78136826/172004523-cf81d33f-786b-488a-83c3-7b39a7bde457.png)
> 
> 

Go to the cmd and put: pip install pytube

**Comment by Patrick1020** [comment]
i realised after that pytube was not installed

**Comment by Patrick1020** [comment]
but now i am getting another one error..

**Comment by Patrick1020** [comment]
![image](https://user-images.githubusercontent.com/78136826/172019221-c0b34fc5-ad57-46be-912b-3a7fd45ab318.png)
![image](https://user-images.githubusercontent.com/78136826/172019230-1d9af5eb-10dd-4b68-ba25-16eba66cf9ab.png)

**Comment by Patrick1020** [comment]
i managed to solve it , i needed to cipher.py that is located "C:\Users\Patrik\AppData\Local\Programs\Python\Python310\Lib\site-packages\pytube\cipher.py " here for me and change this "var_regex = re.compile(r"^\w+\W")" to this "var_regex = re.compile(r"^\$*\w+\W")"
