### ISSUE TITLE
Please explain how to change voice (pls step by step, I'm a noob)

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#44]

**Comment by JasonLovesDoggo** [comment]
1. Go to video_creation/TTSwrapper.py
2. Look at around line 40 for this code
`voice = self.randomvoice() if random_speaker else 'en_us_002'`
3. Look at the list of valid voices as defined on line 4 of that same file.
Replace the en_us_002 with whatever voice you want
4. Run the program

**Comment by mrawesomey** [comment]
I did that, and it comes out like this the title is in the way I want it but the rest isn't?

https://user-images.githubusercontent.com/106691142/172050663-4d254640-6471-42c0-8cbc-22c9018cd4cb.mp4
 (Had to cut it cause of github)
