### ISSUE TITLE
running the temp fix now have to wait ages 

### ISSUE THREAD

**Issue by snappyy** [JasonLovesDoggo/RedditVideoMakerBot#46]
![image](https://user-images.githubusercontent.com/11595540/172028272-5e46f9d5-df80-41c2-9098-1940b76c1c85.png)

using the temp fix branch and as you can see it says like 5 hours is this normal?

**Comment by JasonLovesDoggo** [comment]
Well... The temp fix branch  is in active development and that's why it's not on the main branch so I will not be providing support for code that I have not bug tested yet.

**Comment by snappyy** [comment]
> Well... The temp fix branch is in active development and that's why it's not on the main branch so I will not be providing support for code that I have not bug tested yet.

oh my bad well im running it on a VPS so i'll let it run and go to sleep (im in the UK so its midnight now) will report back in the morning with results
