### ISSUE TITLE
Still getting error "could not find match for ^\w+\W"

### ISSUE THREAD

**Issue by nenoviktor** [JasonLovesDoggo/RedditVideoMakerBot#49]
Still getting the error after editing cipher.py and saving

<img width="1151" alt="Screenshot 2022-06-05 at 12 02 28 PM" src="https://user-images.githubusercontent.com/33195579/172045354-9b981906-2800-4aba-82a5-cb186b7e82ba.png">

**Comment by oVeXz** [comment]
Change `var_regex = re.compile(r"^\w+\W")` with `var_regex = re.compile(r"^\$*\w+\W")` in cypher.py (The location of the file is in the error)

[Check ](https://stackoverflow.com/questions/70776558/pytube-exceptions-regexmatcherror-init-could-not-find-match-for-w-w)

**Comment by nenoviktor** [comment]
that's what im saying I already did that as shown and its still gives error

**Comment by oVeXz** [comment]
I am sorry I did not notice that, you sure the cipher.py is saved correctly. Otherwise reinstall pytube library.

**Comment by oVeXz** [comment]
The error still gives a error for the old line of code not the new one.

**Comment by JasonLovesDoggo** [comment]
Exactly what @oVeXz said.
