### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by nenoviktor** [JasonLovesDoggo/RedditVideoMakerBot#5]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file results/What slang word did you hear t....mp4:

 b'results/What slang word did you hear t....mp4: No such file or directory\n'

**Comment by JasonLovesDoggo** [comment]
Do you see the temp folder?

**Comment by lucacupo** [comment]
It‘s a general bug, not a Mac problem.
You need to create the results folder manually, thats missing.

**Comment by luupo** [comment]
It's a general problem, not a Mac one. The reason for this is the missing "results" folder. Just create it manually and you are good to go.

**Comment by JasonLovesDoggo** [comment]
Either way I added a check to make sure the results folder exists and if not it creates it
