### ISSUE TITLE
Why do the comments (and backgrounds.mp4) not get deleted with cleanup.py 

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#53]
Pls tell me how to fix

**Comment by StopmotionSimonYT** [comment]
It isn't a problem because when you run the program again, it overwrites the images

**Comment by mrawesomey** [comment]
Oh ok and what about backgrounds.mp4 ?

**Comment by StopmotionSimonYT** [comment]
> Oh ok and what about backgrounds.mp4 ?
> 

Same

**Comment by mrawesomey** [comment]
Ah K thx alot
