### ISSUE TITLE
IDEA: Adding a photo in the middle of the video

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#54]
For example to add subscribe or follow or something like that for a second or two in the middle of the video. if that's possible

**Comment by JasonLovesDoggo** [comment]
Hmm. Do you mean like interrupting the normal video?

**Comment by justexistingnow** [comment]
Not neccerialy. for example above of the reddit screenshot you can add a png photo with a transparent background that say "subscribe" for example to prompt people to subscribe

**Comment by JasonLovesDoggo** [comment]
Hmm.
Because this isn't really adding much this will probably be right there at the bottom of the to-do list but it will be implemented nonetheless.

**Comment by justexistingnow** [comment]
No problem at all its just a suggestion! Bug fixes and stuff like that is way more important, but this would be a good addition after all the important fixes/enhancements are added since its mainly used for youtube/tiktok.
