### ISSUE TITLE
How do you change the voice?

### ISSUE THREAD

**Issue by mlvps** [JasonLovesDoggo/RedditVideoMakerBot#57]

**Comment by PatatjeMC** [comment]
1. Open the file video_creation/TTSwrapper.py
2.  ![image](https://user-images.githubusercontent.com/85753923/172185264-ea58af7d-d3c8-4cfe-ad0b-964f3350c6ec.png)
  In this line change the en_us_002 to the voice you want for the title
3.  ![image](https://user-images.githubusercontent.com/85753923/172185368-353b4ac0-d1bb-4fe1-900c-915f7266d853.png)
In this line change the voices to the voices you want or if you want it to randomly select for the comments. (The good ones are higher chance of getting selected)
4. ![image](https://user-images.githubusercontent.com/85753923/172185870-c3cd5c39-1a35-4eb8-8fca-d0fae7bd0f24.png)
If you to change the comments to the same one as the title go to video_creation/voices.py and change the random_speaker to False in this line
