### ISSUE TITLE
IDEA: Add manual comment editing

### ISSUE THREAD

**Issue by PixelNinja132** [JasonLovesDoggo/RedditVideoMakerBot#59]
I think it would be cool to be able to edit comments right before they get put through the TTS allowing us to fix grammar and remove bad characters. This could also work to fully remove a comment if it isn't any good.

**Comment by JasonLovesDoggo** [comment]
i've automated removing bad characters and this is supposed to be a 1 click thing not a big GUI

**Comment by PixelNinja132** [comment]
Removing bad characters doesn't cover grammar or comments that you just don't want in the video

**Comment by JasonLovesDoggo** [comment]
> Removing bad characters doesn't cover grammar or comments that you just don't want in the video
true, but that's the life of this, it's one click
