### ISSUE TITLE
OSError: input_filepath assets\temp\mp3\0.mp3 does not exist.

### ISSUE THREAD

**Issue by tianiste** [JasonLovesDoggo/RedditVideoMakerBot#6]
![image](https://user-images.githubusercontent.com/104372439/171421711-37ce5b5b-7d38-456b-9cb7-54c7502d9498.png)

**Comment by Denotess** [comment]
Got another issue:
![image](https://user-images.githubusercontent.com/104372439/171423329-1361de98-af84-48e5-bfa4-da41122a5f40.png)

**Comment by Denotess** [comment]
New issue again: 
![image](https://user-images.githubusercontent.com/104372439/171424008-532577d8-8e50-411c-891a-077e7483d640.png)

**Comment by Denotess** [comment]
Fixed it by creating a results folder.
