### ISSUE TITLE
Error when creating final video.

### ISSUE THREAD

**Issue by FluxYT** [JasonLovesDoggo/RedditVideoMakerBot#60]
Traceback (most recent call last):
  File "C:\Users\BLANK\Downloads\VidMaker\main.py", line 47, in <module>
    main()
  File "C:\Users\BLANK\Downloads\VidMaker\main.py", line 34, in main
    final_video = make_final_video(number_of_comments, length)
  File "C:\Users\BLANK\Downloads\VidMaker\video_creation\final_video.py", line 38, in make_final_video
    "center").resize(width=W - 100).set_opacity(float(opacity)), )
ValueError: could not convert string to float: ''

**Comment by deman2660** [comment]
yeah im having the same problem here

**Comment by PixelNinja132** [comment]
I experienced this issue when I had the opacity set to 1, try setting it to 0.99 or what I like, 0.9.

**Comment by JasonLovesDoggo** [comment]
Hmm I will add a check to see if the opacity is at one later

**Comment by FluxYT** [comment]
Yeah it's just whenever you don't set an opacity value. I did 0.8 after it failed.

**Comment by JasonLovesDoggo** [comment]
> Yeah it's just whenever you don't set an opacity value. I did 0.8 after it failed.

I'mma add a check see if opacity was at
