### ISSUE TITLE
Is there any chance I can choose what background for the video

### ISSUE THREAD

**Issue by Progaming19199** [JasonLovesDoggo/RedditVideoMakerBot#63]
Is there any chance I can choose what background for the video. I only want the minecraft background and not the Rocket League one

**Comment by JasonLovesDoggo** [comment]
sure
go to video_creation/background.py
look for this code (should be around line 21)

`(
            "https://www.youtube.com/watch?v=2X9QGY__0II",
            "rocket_league.mp4",
            "Orbital Gameplay",
        ),`

and delete it.
