### ISSUE TITLE
IDEA: Make the bot choose threads with a number of upvotes over a certain amount

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#65]
For example only make a video on it if it has 1k upvotes

**Comment by JasonLovesDoggo** [comment]
It doesn't specifically have a minimum requirement right now but it sorts by hot
And in AskReddit to be on hot you have to be having like 3,000 plus updoots

Either way it's a good idea and the updoot counter will be implemented

**Comment by justexistingnow** [comment]
Oh I didn't know it sorted by hot, apparently i went through all of them then because the ones i am getting right now only have like 100-200 upvotes, No rush thanks!

**Comment by JasonLovesDoggo** [comment]
It's currently 11:30 for me right now so I can't really work on it tonight but it should be implemented either tomorrow or relatively soon
