### ISSUE TITLE
[HELP ME]

### ISSUE THREAD

**Issue by JasonLovesDoggo** [JasonLovesDoggo/RedditVideoMakerBot#68]
I am struggling to get the [example video](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/tree/master/examples) to show up in the readme

please help me.

**Comment by BudzynskiMaciej** [comment]
You need to drop mp4 on GitHub markdown editor to get link.

Ref.: https://stackoverflow.com/a/4279746/1092815

**Comment by JasonLovesDoggo** [comment]
> You need to drop mp4 on GitHub markdown editor to get link.
> 
> Ref.: https://stackoverflow.com/a/4279746/1092815

thanks.
I was STRUGGLING with this
