### ISSUE TITLE
Question: How to change the video length?

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#70]
I am sorry if this has been asked and answered before, I looked through the issues and haven't from it I also looked through some of the code and couldn't find it.

**Comment by JasonLovesDoggo** [comment]
> Keep in mind it will not be exactly that length and it could be more by 20 seconds or more but it should be around that area

**Comment by JasonLovesDoggo** [comment]
https://github.com/JasonLovesDoggo/RedditVideoMakerBot/blob/master/video_creation/voices.py#L13

I will be making this into a .Env config though
