### ISSUE TITLE
New error with playwright

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#73]
So I have downloaded new code and now this happens

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

(sorry for no pictures)

**Comment by JasonLovesDoggo** [comment]
please show the full traceback.

**Comment by mrawesomey** [comment]
It works now I just had to restart it and download it again so it works now 
Sorry for bothering.

**Comment by PixelNinja132** [comment]
Reopen, this is an issue still. I have a traceback which is persistent:
![image](https://user-images.githubusercontent.com/41830820/173208382-305dac74-7b31-4a07-926b-6cf0dc9f6f60.png)

**Comment by JasonLovesDoggo** [comment]
try adding
`from playwright.async_api import async_playwright`
to the top of the file

**Comment by PixelNinja132** [comment]
This is still an issue even with the fix.

**Comment by JasonLovesDoggo** [comment]
I don't know what you mean, send me a screenshot of the top of the file with the imports

I haven't had any errors since I made the fjx

**Comment by PixelNinja132** [comment]
Ok, I believe these are the steps:

 - Replace the playwright import line (5) with this:
 `from playwright.async_api import async_playwright, ViewportSize`
- Change `with sync_playwright() as p:` to `with async_playwright() as p:` on L23

**Comment by PixelNinja132** [comment]
Now throws:
![image](https://user-images.githubusercontent.com/41830820/174313306-e67a2d0c-2e8f-45e1-9637-e933667c52ba.png)

**Comment by PixelNinja132** [comment]
Making 11 and 23 run as async fixes this. 

11: `async def download_screenshots_of_reddit_posts(reddit_object, screenshot_num):`
23: `async with async_playwright() as p:`

**Comment by PixelNinja132** [comment]
Yeah I'm clueless, it isn't downloading any screenshots

**Comment by JasonLovesDoggo** [comment]
Don't reinvent the wheel just reclone the code and keep the fix

**Comment by PixelNinja132** [comment]
Surely just importing the async method does nothing since you don't use it.

**Comment by JasonLovesDoggo** [comment]
> Surely just importing the async method does nothing since you don't use it.

Actually it does
The async check only checks if it's imported not if it's used Don't question the fix

**Comment by PixelNinja132** [comment]
Alr ty
