### ISSUE TITLE
IDEA NOT AN ISSUE: add silent background music, just like the background video add the music from a 10 hour popular music loop.

### ISSUE THREAD

**Issue by Denotess** [JasonLovesDoggo/RedditVideoMakerBot#8]

**Comment by JasonLovesDoggo** [comment]
shoot, I'm sorry I got caught up with other things and it's already 11 for me...
will try to do asap

**Comment by JasonLovesDoggo** [comment]
note to self:
moviepy.ffmpeg_tools.ffmpeg_merge_video_audio('after.mp4', 'audio.wav', 'new.mp4')

**Comment by JasonLovesDoggo** [comment]
@Denotess question.

what did you mean by silent in "silent background music"

**Comment by Denotess** [comment]
Just like background music, just not very loud

**Comment by JasonLovesDoggo** [comment]
Still believe it's kind of pointless as you would want to hear the tts engine but nonetheless, it shall be done.
