### ISSUE TITLE
ModuleNotFoundError: No module named 'pytube'

### ISSUE THREAD

**Issue by LeonNussbaum** [JasonLovesDoggo/RedditVideoMakerBot#83]
I have the following problem setting up the bot on my machine (after stating main.py)
![grafik](https://user-images.githubusercontent.com/91377653/173077430-fd7cb3f5-5b4e-46fa-a101-ad1837941c79.png)

```
PS C:\Users\Leon\Desktop\RedditVideoMakerBot-master> python3 main.py                 
Traceback (most recent call last):
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\main.py", line 9, in <module>
    from video_creation.background import download_background, chop_background_video
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\video_creation\background.py", line 5, in <module>
    from pytube import YouTube
ModuleNotFoundError: No module named 'pytube'
```

**Comment by JasonLovesDoggo** [comment]
Try
pip install pytube

**Comment by StopmotionSimonYT** [comment]
Have you tried this?
`pip3 install pytube`

**Comment by Norbertschaefer** [comment]
yes it tried 

`pip3 install pytube`

**Comment by JasonLovesDoggo** [comment]
Try pip install -r requirements.txt

**Comment by Norbertschaefer** [comment]
I installt it like in the Doc still same problem.

**Comment by officialLucas** [comment]
I have the same problem even though I followed all the installation instructions.

**Comment by JasonLovesDoggo** [comment]
That's a python issue
Not my code

**Comment by officialLucas** [comment]
I have now fixed the previous error, but now I get this error:
![image](https://user-images.githubusercontent.com/59314038/173086436-0f5c0ccb-b1dc-41dd-a9b5-3332f2fd1cac.png)

**Comment by Norbertschaefer** [comment]
Same on my site :(

**Comment by Anjo8021** [comment]
> I have now fixed the previous error, but now I get this error: ![image](https://user-images.githubusercontent.com/59314038/173086436-0f5c0ccb-b1dc-41dd-a9b5-3332f2fd1cac.png)

I got that as well

**Comment by JasonLovesDoggo** [comment]
Unfortunately I cannot fix that right now as I am in the emergency room so uhhh

**Comment by aiden-z-source** [comment]
Try `python3 -m pip install pytube`

**Comment by JasonLovesDoggo** [comment]
Fixed in the latest version
