### ISSUE TITLE
How do I make the loop keep running in spite of the error?

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#84]
I would like the loop to continue running even if I get this error:
![image](https://user-images.githubusercontent.com/106691142/173130238-7ffeec5c-e572-4a3b-82c6-512872a940e6.png)
How do I do this or is not possible?

**Comment by StopmotionSimonYT** [comment]
I also want the same and I made an change to the main.py to make this possible. It prints the error in red but reruns the code. You can view it here: https://gist.github.com/StopmotionSimonYT/aa4424e753ad33d6340f04a73bcd8e72
Just replace the code in my Github Gist with your main.py

**Comment by JasonLovesDoggo** [comment]
Thanks

**Comment by JasonLovesDoggo** [comment]
Can't merge it right now as I am in the ER

**Comment by StopmotionSimonYT** [comment]
> Does this fix the ID issue? No matter what ID I use it won't work.

No this is just a code that reruns the script if there is an error. This doesn't solve any error.

**Comment by mrawesomey** [comment]
> I also want the same and I made an change to the main.py to make this possible. It prints the error in red but reruns the code. You can view it here: https://gist.github.com/StopmotionSimonYT/aa4424e753ad33d6340f04a73bcd8e72 Just replace the code in my Github Gist with your main.py

But it doesnt have this stuff :
if __name__ == "__main__":
    try:
        if getenv("TIMES_TO_RUN") and isinstance(int(getenv("TIMES_TO_RUN")), int):
            run_many(int(getenv("TIMES_TO_RUN")))
        else:
            main()
    except KeyboardInterrupt:
        print_markdown("## Clearing temp files")
        cleanup()
        exit()

**Comment by mrawesomey** [comment]
In your its only:
if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print_markdown("## Clearing temp files")
        cleanup()
        exit()

**Comment by mrawesomey** [comment]
Which should I put in my code?

**Comment by mrawesomey** [comment]
Also, now that I put your code in mine, it runs infinitely until I stop it.

**Comment by StopmotionSimonYT** [comment]
My code is a loop until you stop it by exiting the command prompt. With my code it displays the error but reruns the script.
