### ISSUE TITLE
PULL REQUEST: Reruns the script if there is an error

### ISSUE THREAD

**Issue by StopmotionSimonYT** [JasonLovesDoggo/RedditVideoMakerBot#85]
Hello, I don't know how to create a pull request on Github. So I do it in this way. I have made a code that reruns the program if there is an error. It still prints the error. The code is accessible via this link: https://gist.github.com/StopmotionSimonYT/aa4424e753ad33d6340f04a73bcd8e72

**Comment by JasonLovesDoggo** [comment]
Kk can't implement it today

**Comment by mrawesomey** [comment]
Now it runs infinitely without stopping at the Number I told it to stop at

**Comment by JasonLovesDoggo** [comment]
> Now it runs infinitely without stopping at the Number I told it to stop at
> 

That's what that code does

Want to stop at a number and use the default code

**Comment by JasonLovesDoggo** [comment]
> Now it runs infinitely without stopping at the Number I told it to stop at
> 

That's what that code does

Want to stop at a number and use the default code
