### ISSUE TITLE
Possible for widescreen option for youtube videos?

### ISSUE THREAD

**Issue by floridabricks** [JasonLovesDoggo/RedditVideoMakerBot#86]
Is it possible to have 2 formats? 1 vertical for tiktok and the other option widescreen for youtube?

**Comment by StopmotionSimonYT** [comment]
You can change the resolution in the final_video.py

**Comment by floridabricks** [comment]
> You can change the resolution in the final_video.py

Thanks! Will this also resize the reddit screenshots to fit on widescreen?

**Comment by StopmotionSimonYT** [comment]
I think so

**Comment by JasonLovesDoggo** [comment]
You might have to change that in screenshot downloader.py

**Comment by StopmotionSimonYT** [comment]
Is this issue solved?

**Comment by StopmotionSimonYT** [comment]
Do you have the correct post id?

**Comment by floridabricks** [comment]
> Do you have the correct post id?

Yes, you can test it if you want. v98o6f post id CryptoCurrency subreddit

**Comment by floridabricks** [comment]
Every post id I use it keeps giving me this. But if I enter no id it works fine

Launching Headless Browser...
Traceback (most recent call last):
  File "C:\Users\Downloads\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\main.py", line 62, in <module>
    main()
  File "C:\Users\Downloads\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\main.py", line 41, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\Downloads\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 48, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(
  File "C:\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13249, in screenshot
    self._sync(
  File "C:\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Python310\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Python310\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Python310\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Python310\lib\site-packages\playwright\_impl\_frame.py", line 293, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================

**Comment by StopmotionSimonYT** [comment]
The error means that it can't find the title in html. If you visit the website in your normal browser, does it load and view the page?

**Comment by floridabricks** [comment]
> The error means that it can't find the title in html. If you visit the website in your normal browser, does it load and view the page?

Yes the title and page is loading in the browser. But no ID is working for downloading the posts and comments and I'm not sure why. If I leave the ID blank it works perfectly fine.

**Comment by mrawesomey** [comment]
I did all of the the stps to make it wide but now it comes out like this:

**Comment by JasonLovesDoggo** [comment]
> I did all of the the stps to make it wide but now it comes out like this
> 
> https://user-images.githubusercontent.com/106691142/173186844-5c68e318-d36e-4b1d-8d7e-7693cfa68004.mp4
> 
> :

Change the resolution that the screenshots are taken at

**Comment by StopmotionSimonYT** [comment]
Go to video_creation/screenshot_downloader.py:40 . I don't know what the correct value is for 16:9 resolution but you can try different values.

**Comment by justexistingnow** [comment]
I did this and it worked, 
Go to video creation, final_video.py
Change line 21 to W, H = 1920, 1080
Change line 33 to 
.crop(x1=0, y1=0, x2=2246.6, y2=0)
I am using an older version so the lines might be in a different number but find them and change them to this and itll work

**Comment by JasonLovesDoggo** [comment]
> I did this and it worked, 
> Go to video creation, final_video.py
> Change line 21 to W, H = 1920, 1080
> Change line 33 to 
> .crop(x1=0, y1=0, x2=2246.6, y2=0)
> I am using an older version so the lines might be in a different number but find them and change them to this and itll work

Thanks for that I will add it when I can

**Comment by mrawesomey** [comment]
> .crop(x1=0, y1=0, x2=2246.6, y2=0)

Please make the Title and comments smaller in the wide screen video 
Thank you

**Comment by justexistingnow** [comment]
> juste

No problem!

**Comment by justexistingnow** [comment]
> > I did this and it worked,
> > Go to video creation, final_video.py
> > Change line 21 to W, H = 1920, 1080
> > Change line 33 to
> > .crop(x1=0, y1=0, x2=2246.6, y2=0)
> > I am using an older version so the lines might be in a different number but find them and change them to this and itll work
> 
> Thanks for that I will add it when I can

No problem!
