### ISSUE TITLE
ValueError: file_type elements must be one of

### ISSUE THREAD

**Issue by TristanJohnsonpng** [JasonLovesDoggo/RedditVideoMakerBot#87]
![image](https://user-images.githubusercontent.com/79427651/173173696-12e98663-6a12-4744-af31-ed3c73d9838e.png)

**Comment by TristanJohnsonpng** [comment]
we need a fix for this issue i looked through other issues and this appears to be a recurring one

**Comment by Taze00** [comment]
same error here

**Comment by JasonLovesDoggo** [comment]
I'm sorry but as my finger is currently cut in half I cannot fix any bugs

**Comment by TristanJohnsonpng** [comment]
oh okay we will just wait

**Comment by JasonLovesDoggo** [comment]
Fixed
