### ISSUE TITLE
This install of SoX cannot process .mp3 files

### ISSUE THREAD

**Issue by wasay-a99** [JasonLovesDoggo/RedditVideoMakerBot#88]
Getting this error. Everything worked ok until I set the script to repeat 10 times. On the 5th iteration I got this error, and now this error keeps coming up on every iteration.

Input formats were only specified for 0 out of 2 files.The last 2 files will remain unformatted.

![Screenshot 2022-06-11 182122](https://user-images.githubusercontent.com/80226090/173206792-3d7d20f9-af20-4cf6-9638-a7ab70e77a94.jpg)

**Comment by justexistingnow** [comment]
Getting the same error but with a much longer trace back, And i haven't set the script to repeat at all
`
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
Input formats were only specified for 0 out of 2 files.The last 2 files will remain unformatted.
This install of SoX cannot process .mp3 files.
Saving... ----------------------------------------   0% -:--:--
Traceback (most recent call last):
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\main.py", line 62, in <module>
    main()
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\main.py", line 40, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\video_creation\voices.py", line 51, in save_text_to_mp3
    ttttsw.tts(
  File "C:\Users\blank-\OneDrive\Documents\Reddit project\Jason Multi Updated\RedditVideoMakerBot\video_creation\TTSwrapper.py", line 125, in tts
    cbn.build(audio_clips, filename, "concatenate")
  File "C:\Python310\lib\site-packages\sox\combine.py", line 87, in build
    _validate_file_formats(input_filepath_list, combine_type)
  File "C:\Python310\lib\site-packages\sox\combine.py", line 319, in _validate_file_formats
    _validate_sample_rates(input_filepath_list, combine_type)
  File "C:\Python310\lib\site-packages\sox\combine.py", line 328, in _validate_sample_rates
    sample_rates = [
  File "C:\Python310\lib\site-packages\sox\combine.py", line 329, in <listcomp>
    file_info.sample_rate(f) for f in input_filepath_list
  File "C:\Python310\lib\site-packages\sox\file_info.py", line 205, in sample_rate
    output = soxi(input_filepath, 'r')
  File "C:\Python310\lib\site-packages\sox\core.py", line 147, in soxi
    shell_output = subprocess.check_output(
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

`

**Comment by wasay-a99** [comment]
Yep me too, I realized I didn't copy the whole  trace back, but mine is very similar to yours. I find it sometimes works, and sometimes doesn't. I got no idea what's causing it

**Comment by TristanJohnsonpng** [comment]
got same error

**Comment by StopmotionSimonYT** [comment]
Do you have SoX installed via the sourceforge or `pip3 install SoX`?

**Comment by JasonLovesDoggo** [comment]
Try installing python 3.8 +

**Comment by wasay-a99** [comment]
I initially used sourceforge, I got another error (Issue #79 ) then used pip3 install SoX.

**Comment by wasay-a99** [comment]
Should I uninstall my current version of python first? Or would the new version automatically replace the previous?

**Comment by wasay-a99** [comment]
Just reinstalled, same error

**Comment by wasay-a99** [comment]
> Do you have SoX installed via the sourceforge or `pip3 install SoX`?

I installed SoX using 'pip3 install SoX'

**Comment by JasonLovesDoggo** [comment]
> > Do you have SoX installed via the sourceforge or `pip3 install SoX`?
> 
> I installed SoX using 'pip3 install SoX'

Dude you can't expect me to help you if you don't follow the documentation.

**Comment by wasay-a99** [comment]
I initially installed SoX using Sourceforge, per the documentation. then I got the same error mentioned in issue #79. The fix there was to use '`pip3 install sox`' instead. 

I am new to GitHub, I figured if the issue was marked as resolved, then the solution was approved by the owner.

**Comment by Mannlig** [comment]
Hey, I just got the same issue after creating the first video. 
Could it be that there are some files that I need to delete before I can run the program again?

**Comment by justexistingnow** [comment]
> > > Do you have SoX installed via the sourceforge or `pip3 install SoX`?
> > 
> > 
> > I installed SoX using 'pip3 install SoX'
> 
> Dude you can't expect me to help you if you don't follow the documentation.

I got python 3.10 installed and installed SoX via sourceforge and it gives me the same error, It doesn't on the older version of the bot, And sometimes this version works and sometimes it gives the error

**Comment by LeonNussbaum** [comment]
> 

Same

**Comment by Pogues2K** [comment]
1. Go to My Computer → Properties → Advanced System Settings → Environment Variables → System variables.
2. Select Path.
3. Click Edit → New :
4. Add this: C:\Program Files (x86)\sox-<CHECK YOUR VERSION NUMBER>\
5. As indicated in the example path, make sure to check what version of Sox you have installed by actually navigating to your Program Files (x86) folder and looking for a folder that starts with sox, for example sox-14-4-2.
6. Restart your terminal.
7. Note that if you're using an IDE, you may need to restart the IDE to have the Path variables update.

**Comment by wasay-a99** [comment]
![image](https://user-images.githubusercontent.com/80226090/173735282-e6c2e961-bfa5-44b0-abe7-ddf0da5661c1.png)
I entered this under System variables, reset my terminal using `shutdown -t 0 -r -f` , and still get the same error.

**Comment by CJthisis** [comment]
The original project doesn't use SoX and eventhough i cant get a video to render in this fork, the original works totally fine. Is there a way to bypass or replace SoX with something else? (Since it seems to cause the problems)

**Comment by CJthisis** [comment]
Ok, i have found a way to solve this issue (i think).

You have to make an entry in the 'Path' in the System variables, but you have to move that new entry with the sox folder all the way to the top in the list of paths in the 'Path' variable

**Comment by ArshadhAX** [comment]
> 

How do I do this?
