### ISSUE TITLE
[Enhancement] Add a like and subscribe prompt to the end

### ISSUE THREAD

**Issue by PixelNinja132** [JasonLovesDoggo/RedditVideoMakerBot#89]
Okay, so I did some testing, and I worked on a hacky method for automatically adding a like and subscribe prompt by just getting it to add the image and audio automatically when it adds the comments in the loop. From those videos, I saw an average increase of 348% in likes and subscribers per video. This could be added in a few lines, and also have an option to disable it in the .ENV file. I'd be happy to share my code, but it would def need improvement since I don't normally work in Python

**Comment by justexistingnow** [comment]
Do you mind sharing the code please?

**Comment by PixelNinja132** [comment]
No problem at all! I'll clean it up and then post it here ASAP. My videos are currently 50 seconds long before adding the like and subscribe message, so about 55 seconds.

**Comment by justexistingnow** [comment]
That would be great I really appreciate it! Btw i'd love to see your channel you could send me the link, if you don't mind

**Comment by PixelNinja132** [comment]
Implementation Steps are rough and are not fully automatic, so some additional code must be written:

1. Create the audio clip for the end of the video. I did this by setting one of the comments to the text, then saving the MP3 that it saved. An issue with this is that it only uses one fixed voice.
2. On line 22 of voices.py, set the length to the same length as your end of the video audio clip, mine was 6 seconds.
3. Get the MP3 and subscribe image and put it in the assets folder
4. Add this code in final_video.py:

![image](https://user-images.githubusercontent.com/41830820/173209345-ea54cbf9-6bba-45dc-b8e5-12a3822316ad.png)
![image](https://user-images.githubusercontent.com/41830820/173209353-5e6e2bc0-f8e3-4f2e-be89-1d184621d08d.png)


I think that is everything?

**Comment by justexistingnow** [comment]
Thanks will try it

**Comment by justexistingnow** [comment]
by the way! Would you mind sharing the link to your channel? if not its fine!

**Comment by justexistingnow** [comment]
When I implement the code, It starts the image half way though the video

**Comment by PixelNinja132** [comment]
> When I implement the code, It starts the image and tts half way though the video

I'll need to see the code for this. You need to make sure the screenshot and audio clip is at the end of the array. I'm not currently sharing my Youtube channel since I'm measuring stats, and I have a Youtube channel that has enough subscribers to make the test unfair since I do code-related things using Github (Not tons, but enough that it could gain more subscribers and make this test unfair).

**Comment by mrawesomey** [comment]
> Implementation Steps are rough and are not fully automatic, so some additional code must be written:
> 
> 1. Create the audio clip for the end of the video. I did this by setting one of the comments to the text, then saving the MP3 that it saved. An issue with this is that it only uses one fixed voice.
> 2. On line 22 of voices.py, set the length to the same length as your end of the video audio clip, mine was 6 seconds.
> 3. Get the MP3 and subscribe image and put it in the assets folder
> 4. Add this code in final_video.py:
> 
> ![image](https://user-images.githubusercontent.com/41830820/173209345-ea54cbf9-6bba-45dc-b8e5-12a3822316ad.png) ![image](https://user-images.githubusercontent.com/41830820/173209353-5e6e2bc0-f8e3-4f2e-be89-1d184621d08d.png)
> 
> I think that is everything?

Should the subscribe.png have a transparent background?

**Comment by StopmotionSimonYT** [comment]
> > Implementation Steps are rough and are not fully automatic, so some additional code must be written:
> > 
> > 1. Create the audio clip for the end of the video. I did this by setting one of the comments to the text, then saving the MP3 that it saved. An issue with this is that it only uses one fixed voice.
> > 2. On line 22 of voices.py, set the length to the same length as your end of the video audio clip, mine was 6 seconds.
> > 3. Get the MP3 and subscribe image and put it in the assets folder
> > 4. Add this code in final_video.py:
> > 
> > ![image](https://user-images.githubusercontent.com/41830820/173209345-ea54cbf9-6bba-45dc-b8e5-12a3822316ad.png) ![image](https://user-images.githubusercontent.com/41830820/173209353-5e6e2bc0-f8e3-4f2e-be89-1d184621d08d.png)
> > 
> > I think that is everything?
> 
> Should the subscribe.png have a transparent background?
> 

I think it doesn't matter. But in my opinion a transparent background looks better

**Comment by mrawesomey** [comment]
> > > Implementation Steps are rough and are not fully automatic, so some additional code must be written:
> > > 
> > > 1. Create the audio clip for the end of the video. I did this by setting one of the comments to the text, then saving the MP3 that it saved. An issue with this is that it only uses one fixed voice.
> > > 2. On line 22 of voices.py, set the length to the same length as your end of the video audio clip, mine was 6 seconds.
> > > 3. Get the MP3 and subscribe image and put it in the assets folder
> > > 4. Add this code in final_video.py:
> > > 
> > > ![image](https://user-images.githubusercontent.com/41830820/173209345-ea54cbf9-6bba-45dc-b8e5-12a3822316ad.png) ![image](https://user-images.githubusercontent.com/41830820/173209353-5e6e2bc0-f8e3-4f2e-be89-1d184621d08d.png)
> > > I think that is everything?
> > 
> > 
> > Should the subscribe.png have a transparent background?
> 
> I think it doesn't matter. But in my opinion a transparent background looks better

Also in which line  should I put it in the newest code

**Comment by StopmotionSimonYT** [comment]
I am on my phone so checking which line is not so easy. Can't you figure out where to put it by the other lines above the code that already are in your code?

You can try putting a video in the line and see what it does.

**Comment by mrawesomey** [comment]
Also wizh a transparent background or green screen

**Comment by PixelNinja132** [comment]
To everyone above, like I said, this is a rough implementation. If you don't have python knowledge to add the images and audio to the directories, then use my rough code to add to your existing implementation, you will have to wait for an official version to launch since I do not have the skills to provide support.

**Comment by mrawesomey** [comment]
If someone can pls make it so I can do it with a video 
Thanks

**Comment by PixelNinja132** [comment]
Look, nobody can help you without code. On top of that, this is a Github thread which isn't best for getting support implementing something like this.
