### ISSUE TITLE
Stuck on downloading video

### ISSUE THREAD

**Issue by TristanJohnsonpng** [JasonLovesDoggo/RedditVideoMakerBot#90]
Ik your at the emergency room but when your out fix this error.
![image](https://user-images.githubusercontent.com/79427651/173208709-d6ae886a-5979-4836-b96b-54f8a6fe20a2.png)

**Comment by JasonLovesDoggo** [comment]
dude it said please be patient.

the speed that it downloads on depends on your wifi.
