### ISSUE TITLE
Timeout Exceed

### ISSUE THREAD

**Issue by RatchanonDev** [JasonLovesDoggo/RedditVideoMakerBot#92]
![image](https://user-images.githubusercontent.com/65711396/173230953-281cbb67-1a48-405f-b81b-956699b50009.png)

**Comment by StopmotionSimonYT** [comment]
The error means that the page couldn't load. If you navigate to the website in your normal browser, does the page load?

**Comment by RatchanonDev** [comment]
It loaded normally but take like 10 seconds.

**Comment by StopmotionSimonYT** [comment]
I don't know how to do that but I found this page that might be helpful. https://stackoverflow.com/questions/67787470/playwright-js-how-to-globally-define-change-timeout-if-element-selector-not-fo

**Comment by RatchanonDev** [comment]
I tried page.setDefaultNavigationTimeout(5000000) and I got 'Page' object has no attribute 'setDefaultNavigationTimeout' is there other way to make it work? Because I can go to the page on my browser normally

**Comment by StopmotionSimonYT** [comment]
Maybe `context.setDefaultNavigationTimeout(5000000)`?

**Comment by RatchanonDev** [comment]
It turns out I opened wrong docs and that was for javascript the correct one should be page.set_default_navigation_timeout(5000000)

**Comment by RatchanonDev** [comment]
now its not showing any error atm and is at downloading screenshots

**Comment by RatchanonDev** [comment]
How long should the Downloading Screenshots Take?

**Comment by StopmotionSimonYT** [comment]
I don't know why it is so slow. At my computer the screenshots are downloaded after about 20 seconds. Are there appearing new screenshots?

**Comment by RatchanonDev** [comment]
> I don't know why it is so slow. At my computer the screenshots are downloaded after about 20 seconds. Are there appearing new screenshots?

 New One is appearing but it was really slow. My Internet Download Speed is 500 Mbps

**Comment by RatchanonDev** [comment]
Wait I got another error. it's downloading the background video and this show up.
![image](https://user-images.githubusercontent.com/65711396/173231982-fc07b152-4a01-4110-91e7-80171153f30e.png)

**Comment by StopmotionSimonYT** [comment]
I don't know why it is so slow downloading. If you open task manager, is your system highly used? That can be the cause of the problem.

**Comment by RatchanonDev** [comment]
> Wait I got another error. it's downloading the background video and this show up. ![image](https://user-images.githubusercontent.com/65711396/173231982-fc07b152-4a01-4110-91e7-80171153f30e.png)

what about this one

**Comment by StopmotionSimonYT** [comment]
> Wait I got another error. it's downloading the background video and this show up.
> ![image](https://user-images.githubusercontent.com/65711396/173231982-fc07b152-4a01-4110-91e7-80171153f30e.png)
> 
> 

If you open that URL in your main browser, how long does it take to view the video?

**Comment by StopmotionSimonYT** [comment]
And you can try opening the script in a non-admin CMD.

**Comment by RatchanonDev** [comment]
yo i tried non admin and i am getting this now
![image](https://user-images.githubusercontent.com/65711396/173235763-a550570e-f66b-40d8-8fc4-c3ddf8f4a59b.png)

**Comment by StopmotionSimonYT** [comment]
Your internet is too slow for loading Reddit pages.

**Comment by StopmotionSimonYT** [comment]
Are you using WiFi or ethernet?

**Comment by RatchanonDev** [comment]
> Are you using WiFi or ethernet?

WIFI and it's 500 Mbps so I don't think its that slow tho

**Comment by StopmotionSimonYT** [comment]
I think it is not stable enough so it disconnects.

**Comment by JasonLovesDoggo** [comment]
It's definitely fast enough It just may not be stable enough

**Comment by PixelNinja132** [comment]
Ok, I get this sometimes, I just give it 20 minutes and it just works again.

**Comment by JasonLovesDoggo** [comment]
That's a problem with your internet
