### ISSUE TITLE
Is it possible to read text below title? 

### ISSUE THREAD

**Issue by edvinas1** [JasonLovesDoggo/RedditVideoMakerBot#93]
Hi, as i noticed it just reads tittle but not text below title is it possible to change it and if yes where ?

**Comment by StopmotionSimonYT** [comment]
In video_creation/voices.py:38 STORYMODE is requested from the .env. I don't know what this does but you can give it a try by adding STORYMODE=true in the .env file.

**Comment by StopmotionSimonYT** [comment]
We are working on a story mode.

**Comment by JasonLovesDoggo** [comment]
Please give me time as my finger is literally cut in half right now and I can't use my left arm

If somebody continues my work on that feature I will be happy to merge it but I cannot code at the moment

**Comment by JasonLovesDoggo** [comment]
Duplicate of #10
